version: '3.9'
services:
  app:
    image: ghcr.io/algostract/portfolio-monalisa:latest
    env_file:
      - .env
    volumes:
      - portfolio-monalisa_static:/app/static
      - portfolio-monalisa_data:/app/.data
    expose:
      - 3000
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  portfolio-monalisa_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-monalisa/static
  portfolio-monalisa_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-monalisa/.data

networks:
  front-tier:
    driver: overlay
